name:  ${project.name}
author: Marek2810
main: me.Marek2810.PersoKits.PersoKits
version: ${project.version} 
api-version: 1.13

commands:
  persokits:
    permission: persokits.admin
    permission-message: You do not have permission! 
  kit:    
    permission-message: You do not have permission!
  pkit:
    permission-message: You do not have permission!  
  kiteditor:
    permission: persokits.editor
    permission-message: You do not have permission!
    aliases: [kite, keditor]
    
permissions:
  persokits.kit.*:
    description: Allows to get all kits
    default: op
  persokits.editor:
    description: Allows edit kits
    default: op
  persokits.admin:
    description: Allows reload plugin
    default: op
  persokits.bypass.cooldown:
    description: Bypass kit cooldown
    default: op
  persokits.bypass.uses:
    description: Bypass kit uses
    default: op
